# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 08:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('gender', models.BooleanField(default=1)),
                ('age', models.IntegerField(default=19)),
                ('memo', models.TextField(default='xxx')),
                ('createdate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='typeid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.UserType'),
        ),
    ]
