# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group_relation',
            field=models.ManyToManyField(to='web.Group'),
        ),
    ]
