# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20161025_0843'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='./upload/')),
                ('data', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
