# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-14 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('userid', models.IntegerField(blank=True, max_length=11)),
                ('itype', models.CharField(max_length=50)),
                ('adddate', models.DateTimeField(auto_now_add=True)),
                ('startdate', models.DateField(null=True)),
                ('enddate', models.DateField(null=True)),
                ('content', models.TextField(null=True)),
                ('status', models.IntegerField(choices=[(0, '\u7b49\u5f85'), (1, '\u5f00\u59cb'), (2, '\u5b8c\u6210')], default=0, max_length=4)),
                ('del_userid', models.IntegerField(blank=True, max_length=11)),
                ('del_status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Item_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=11)),
                ('content', models.TextField()),
                ('editdate', models.DateTimeField()),
                ('taskid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inputid', models.IntegerField(max_length=11)),
                ('inputdate', models.DateTimeField(null=True)),
                ('userid', models.IntegerField(max_length=11)),
                ('depid', models.IntegerField(max_length=11)),
                ('assistid', models.IntegerField(max_length=11)),
                ('assdepid', models.IntegerField(max_length=11)),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('enddate', models.DateTimeField(auto_now_add=True)),
                ('begindate', models.DateTimeField(null=True)),
                ('finishdate', models.DateTimeField(null=True)),
                ('evaluate', models.TextField(null=True)),
                ('priority', models.IntegerField(choices=[(0, '\u6700\u4f4e'), (1, '\u666e\u901a'), (2, '\u7d27\u6025')], default=0, max_length=4)),
                ('itemid', models.IntegerField(max_length=11, null=True)),
                ('departmentid', models.IntegerField(max_length=11)),
                ('del_userid', models.IntegerField(max_length=11, null=True)),
                ('del_status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0, max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Task_reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(max_length=11)),
                ('content', models.TextField()),
                ('editdate', models.DateTimeField()),
                ('taskid', models.IntegerField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=11, null=True)),
                ('birthday', models.DateField(null=True)),
                ('sex', models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0, max_length=4)),
                ('qq', models.IntegerField(max_length=11, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('access', models.IntegerField(choices=[(0, '\u666e\u901a'), (1, '\u7ba1\u7406\u5458')], default=0, max_length=4)),
                ('image', models.ImageField(max_length=50, null=True, upload_to=b'')),
                ('adddate', models.DateTimeField(null=True)),
                ('status', models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.Department')),
            ],
        ),
    ]
