# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='del_status',
            field=models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='del_userid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.IntegerField(choices=[(0, '\u7b49\u5f85'), (1, '\u5f00\u59cb'), (2, '\u5b8c\u6210')], default=0),
        ),
        migrations.AlterField(
            model_name='item_reply',
            name='taskid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item_reply',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='assdepid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='assistid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='del_status',
            field=models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='del_userid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='departmentid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='depid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='inputid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(0, '\u6700\u4f4e'), (1, '\u666e\u901a'), (2, '\u7d27\u6025')], default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task_reply',
            name='taskid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='task_reply',
            name='userid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.IntegerField(choices=[(0, '\u666e\u901a'), (1, '\u7ba1\u7406\u5458')], default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0),
        ),
    ]
