# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-17 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20161017_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='userid',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='itemid',
            field=models.IntegerField(null=True),
        ),
    ]
