# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-04 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20161017_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u90e8\u95e8\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='user',
            name='access',
            field=models.IntegerField(choices=[(0, '\u666e\u901a'), (1, '\u7ba1\u7406\u5458')], default=0, verbose_name='\u6743\u9650'),
        ),
        migrations.AlterField(
            model_name='user',
            name='adddate',
            field=models.DateTimeField(null=True, verbose_name='\u52a0\u5165\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, verbose_name='\u751f\u65e5'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='\u90ae\u4ef6'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(max_length=50, null=True, upload_to=b'', verbose_name='\u5934\u50cf\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=20, verbose_name='\u7528\u6237\u540d'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passwd',
            field=models.CharField(max_length=50, verbose_name='\u5bc6\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(null=True, verbose_name='\u7535\u8bdd'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qq',
            field=models.IntegerField(null=True, verbose_name='QQ\u53f7\u7801'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, '\u7537'), (1, '\u5973')], default=0, verbose_name='\u6027\u522b'),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.IntegerField(choices=[(0, '\u6b63\u5e38'), (1, '\u5220\u9664')], default=0, verbose_name='\u7528\u6237\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='\u767b\u5f55\u8d26\u53f7'),
        ),
    ]
